# Generated by Django 5.2.16 on 2026-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKUItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('item_name', models.TextField()),
                ('stock', models.FloatField(default=0.0)),
                ('costo_un', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_tt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('precio_lista', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cod_grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_grupo', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('clase', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('familia', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('subfamilia', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('is_incomplete', models.BooleanField(db_index=True, default=True)),
                ('pending_fields', models.JSONField(default=list)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
                ('ai_rationale', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
