# Generated by Django 5.2.16 on 2026-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuitem',
            name='ai_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='skuitem',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
