# Generated by Django 5.2.16 on 2026-09-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_skuitem_ai_processed_skuitem_ai_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nombre', models.CharField(max_length=150)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_compra', models.CharField(blank=True, help_text='Código SAP del artículo a comprar.', max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_compra', models.CharField(choices=[('stock', 'Stock'), ('calzada', 'Calzada')], default='stock', max_length=10)),
                ('justification', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Compra',
                'verbose_name_plural': 'Solicitudes de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_code', models.CharField(blank=True, help_text='Código correlativo sugerido por el sistema.', max_length=50, null=True)),
                ('solicitante_nombre', models.CharField(help_text='Nombre real o área del solicitante.', max_length=150)),
                ('proposed_description', models.TextField(help_text='Descripción del nuevo ítem (mejorada con IA).')),
                ('justification', models.TextField(help_text='Motivo de la creación del nuevo código.')),
                ('clase_propuesta', models.CharField(blank=True, max_length=100, null=True)),
                ('familia_propuesta', models.CharField(blank=True, max_length=100, null=True)),
                ('subfamilia_propuesta', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_propuesta', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas del administrador al aprobar/rechazar.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_sku', models.ForeignKey(blank=True, help_text='Código SAP de referencia para duplicar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_requests', to='taxonomy.skuitem')),
            ],
            options={
                'verbose_name': 'Solicitud de Creación de Código',
                'verbose_name_plural': 'Solicitudes de Creación de Códigos',
                'ordering': ['-created_at'],
            },
        ),
    ]
