# Generated by Django 5.2.16 on 2026-09-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_add_solicitudes_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecreationrequest',
            name='codigo_catalogo_proveedor',
            field=models.CharField(blank=True, help_text='Código del artículo en el catálogo del proveedor (ej: CSE4P-015).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='es_importado',
            field=models.BooleanField(default=False, help_text='¿El artículo es importado / internacional?'),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='ficha_tecnica',
            field=models.TextField(blank=True, help_text='Especificaciones técnicas del artículo (texto libre).', null=True),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='ficha_tecnica_archivo',
            field=models.FileField(blank=True, help_text='Adjunto de ficha técnica (PDF, JPG, PNG). Máx 20 MB.', null=True, upload_to='fichas_tecnicas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='grupo_material',
            field=models.CharField(blank=True, help_text='Grupo de materiales / área de donde proviene la solicitud (ej: EQUIPOS EPP).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW – Ex Works'), ('FOB', 'FOB – Free on Board'), ('CIF', 'CIF – Cost, Insurance & Freight'), ('DDP', 'DDP – Delivered Duty Paid'), ('DAP', 'DAP – Delivered at Place'), ('NA', 'N/A – No aplica')], default='NA', max_length=5),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='lote_minimo',
            field=models.PositiveIntegerField(blank=True, help_text='Lote mínimo de compra (cantidad mínima que acepta el proveedor).', null=True),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='moneda_precio',
            field=models.CharField(blank=True, choices=[('CLP', 'CLP – Peso Chileno'), ('USD', 'USD – Dólar'), ('EUR', 'EUR – Euro'), ('BRL', 'BRL – Real Brasileño')], default='CLP', max_length=5),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='precio_referencial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio referencial unitario.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='proveedor_nombre',
            field=models.CharField(blank=True, help_text='Nombre del proveedor.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codecreationrequest',
            name='unidad_empaque',
            field=models.CharField(blank=True, help_text='Unidad/medida de empaque (ej: Caja x 12, UN, KG, MT).', max_length=50, null=True),
        ),
    ]
