# Generated by Django 5.2.16 on 2026-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_add_proveedor_ficha_tecnica_grupo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecreationrequest',
            name='lote_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del lote de carga masiva.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='lote_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del lote de carga masiva.', max_length=50, null=True),
        ),
    ]
